dist: trusty
language: node_js
node_js:
  - 10
cache:
  directories:
    # Instead of saving node_modules to the cache,
    # we will save local npm cache, as npm will use
    # ci command to install dependencies
    #
    # https://docs.npmjs.com/cli/ci#example
    - '$HOME/.npm'
jobs:
  include:
    - stage: Tests & Code Check
      name: '[Chromium] Functional Tests'
      script: JEST_BROWSER=chromium npm run test

    - stage: Tests & Code Check
      name: '[Firefox] Functional Tests'
      script: JEST_BROWSER=firefox npm run test

    - stage: Tests & Code Check
      name: '[WebKit] Functional Tests'
      script: JEST_BROWSER=webkit npm run test
