dist: trusty
language: node_js
node_js:
  - 12
cache:
  directories:
    # Instead of saving node_modules to the cache,
    # we will save local npm cache, as npm will use
    # ci command to install dependencies
    #
    # https://docs.npmjs.com/cli/ci#example
    - '$HOME/.npm'
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - npm run test
  - BROWSER=firefox npm run test
  - BROWSER=webkit npm run test
#jobs:
#  include:
#    - stage: Tests & Code Check
#      name: '[Firefox] Tests'
#      script: BROWSER=firefox npm run test
#
#    - stage: Tests & Code Check
#      name: '[Chromium] Tests'
#      script: npm run test
#
#    - stage: Tests & Code Check
#      name: '[WebKit] Tests'
#      script: BROWSER=webkit npm run test
